@startuml DonarDinero
actor Persona
boundary Interfaz_De_Usuario
control ContribucionController

entity FactoryContribucion
entity DonacionDeDineroBuilder
entity Colaborador
database BaseDeDatosContribucion

activate Persona
activate Interfaz_De_Usuario
activate ContribucionController
Persona->Interfaz_De_Usuario: distribucionDeViandas

Interfaz_De_Usuario->ContribucionController: create(Context context)
ContribucionController->ContribucionController: estaLogueado(Context context)


alt No logeado
    ContribucionController->Interfaz_De_Usuario: AccessDeniedException()
    Interfaz_De_Usuario->Persona: Error 401
end

ContribucionController -> Interfaz_De_Usuario: context.render("donarDinero.hbs", model)
Interfaz_De_Usuario -> Persona: context.render("donarDinero.hbs", model)

Persona -> Interfaz_De_Usuario: save(Context context)
Interfaz_De_Usuario -> ContribucionController: save(Context context)
ContribucionController -> FactoryContribucion: factoryMethod(Context context)
activate FactoryContribucion
FactoryContribucion -> FactoryContribucion: donarDinero(Context)
FactoryContribucion -> FactoryContribucion: obtenerColaborador()
activate BaseDeDatosContribucion
FactoryContribucion -> BaseDeDatosContribucion : repo.search(Persona.class,id)
alt No tiene permiso
    FactoryContribucion -> ContribucionController: UnauthorizedResponseException()
    ContribucionController -> Interfaz_De_Usuario: UnauthorizedResponseException
    Interfaz_De_Usuario -> Persona: No tienes permisos
end
BaseDeDatosContribucion -> FactoryContribucion : colaborador
deactivate BaseDeDatosContribucion
FactoryContribucion -> DonacionDeDineroBuilder: construir()
activate DonacionDeDineroBuilder
DonacionDeDineroBuilder -> FactoryContribucion: DonacionDeDinero
deactivate DonacionDeDineroBuilder
activate Colaborador
FactoryContribucion -> Colaborador: generarNuevaDonacion(donacionDeDinero)
Colaborador -> Colaborador: agregarNuevaDonacion(unaDonacion)
Colaborador -> Colaborador: sumarPuntaje(unaDonacion)
FactoryContribucion -> ContribucionController: donacionDeDinero
deactivate Colaborador
FactoryContribucion -> BaseDeDatosContribucion: Repo.agregar(donacionDeDinero)
activate BaseDeDatosContribucion
BaseDeDatosContribucion -> FactoryContribucion: ok
deactivate FactoryContribucion
deactivate BaseDeDatosContribucion
ContribucionController -> Interfaz_De_Usuario: context.redirect("/contribucionExitosa")
deactivate ContribucionController

Interfaz_De_Usuario -> Persona: context.redirect("/contribucionExitosa")

@enduml
