@startuml GenerarDonacionDeVianda
actor PersonaHumana
boundary Interfaz_De_Usuario
control ContribucionController


entity FactoryContribucion
entity DonacionDeViandaBuilder
entity Colaborador
database BaseDeDatosContribucion

activate PersonaHumana
activate Interfaz_De_Usuario
activate ContribucionController
PersonaHumana->Interfaz_De_Usuario: donacionDeVianda

Interfaz_De_Usuario->ContribucionController: create(Context context)
ContribucionController->ContribucionController: estaLogueado(Context context)


alt No logeado
    ContribucionController->Interfaz_De_Usuario: AccessDeniedException()
    Interfaz_De_Usuario->PersonaHumana: Error 401
end

ContribucionController -> Interfaz_De_Usuario: context.render("donacionDeVianda.hbs", model)
Interfaz_De_Usuario -> PersonaHumana: context.render("donacionDeVianda.hbs", model)

PersonaHumana -> Interfaz_De_Usuario: save(Context context)
Interfaz_De_Usuario -> ContribucionController: save(Context context)
deactivate Interfaz_De_Usuario
ContribucionController -> FactoryContribucion: factoryMethod(Context context)

activate FactoryContribucion
FactoryContribucion -> FactoryContribucion: donacionDeVianda(Context)
deactivate ContribucionController
activate DonacionDeViandaBuilder
FactoryContribucion -> DonacionDeViandaBuilder: construir()
DonacionDeViandaBuilder -> FactoryContribucion: donacionDeVianda
deactivate DonacionDeViandaBuilder
FactoryContribucion -> Colaborador: generarNuevaDonacion(donacionDeVianda)
activate Colaborador
Colaborador -> Colaborador: agregarNuevaDonacion(unaDonacion)
Colaborador -> Colaborador: sumarPuntaje(unaDonacion)
FactoryContribucion -> ContribucionController: donacionDeVianda
deactivate Colaborador
deactivate FactoryContribucion
activate ContribucionController
ContribucionController -> BaseDeDatosContribucion: guardar(donacionDeVianda)
activate BaseDeDatosContribucion
deactivate BaseDeDatosContribucion
ContribucionController -> Interfaz_De_Usuario: context.redirect("/contribucionExitosa")
activate Interfaz_De_Usuario
deactivate ContribucionController

Interfaz_De_Usuario -> PersonaHumana: context.redirect("/contribucionExitosa")

@enduml
