@startuml GenerarregistrarTarjeta
actor PersonaHumana
boundary Interfaz_De_Usuario
control ContribucionController


entity FactoryContribucion
entity vulnerableBuilder
entity TarjetaAlimentar
entity Colaborador
entity EntregaDeTarjeta
database BaseDeDatosContribucion

activate PersonaHumana
activate Interfaz_De_Usuario
activate ContribucionController

PersonaHumana->Interfaz_De_Usuario: registrarTarjeta
Interfaz_De_Usuario->ContribucionController: create(Context context)
ContribucionController->ContribucionController: estaLogueado(Context context)


alt No logeado
    ContribucionController->Interfaz_De_Usuario: AccessDeniedException()
    Interfaz_De_Usuario->PersonaHumana: Error 401
end

ContribucionController -> Interfaz_De_Usuario: context.render("hacerseCargoDeHeladera.hbs", model)
Interfaz_De_Usuario -> PersonaHumana: context.render("hacerseCargoDeHeladera.hbs", model)

PersonaHumana -> Interfaz_De_Usuario: save(Context context)
Interfaz_De_Usuario -> ContribucionController: save(Context context)
deactivate Interfaz_De_Usuario
ContribucionController -> FactoryContribucion: factoryMethod(Context context)

activate FactoryContribucion
FactoryContribucion -> FactoryContribucion: registrarTarjeta(Context)
deactivate ContribucionController
activate vulnerableBuilder
deactivate vulnerableBuilder
FactoryContribucion -> vulnerableBuilder: construir()
vulnerableBuilder -> FactoryContribucion: persona
deactivate vulnerableBuilder
activate TarjetaAlimentar
FactoryContribucion -> TarjetaAlimentar : new TarjetaAlimentar(persona)
TarjetaAlimentar -> FactoryContribucion : tarjeta
deactivate TarjetaAlimentar
activate EntregaDeTarjeta
FactoryContribucion -> EntregaDeTarjeta: new EntregaDeTarjeta(tarjeta)
EntregaDeTarjeta -> FactoryContribucion : unaDonacion
deactivate EntregaDeTarjeta

FactoryContribucion -> FactoryContribucion : obtenerColaborador()
FactoryContribucion -> BaseDeDatosContribucion : repo.search(Persona.class,id)
activate BaseDeDatosContribucion

alt No tiene permiso
    FactoryContribucion -> ContribucionController: UnauthorizedResponseException()
    ContribucionController -> Interfaz_De_Usuario: UnauthorizedResponseException
    Interfaz_De_Usuario -> PersonaHumana: No tienes permisos
end
BaseDeDatosContribucion -> FactoryContribucion : Persona
FactoryContribucion -> Colaborador : persona.agregarNuevaDonacion(unaDonacion)
activate Colaborador
Colaborador -> Colaborador: agregarNuevaDonacion(unaDonacion)
Colaborador -> Colaborador: sumarPuntaje(unaDonacion)
deactivate Colaborador
deactivate BaseDeDatosContribucionr
FactoryContribucion -> BaseDeDatosContribucion: Repo.agregar(persona);
FactoryContribucion -> BaseDeDatosContribucion: Repo.modificar(colaborador);
FactoryContribucion -> ContribucionController: ok
deactivate FactoryContribucion
activate ContribucionController
deactivate BaseDeDatosContribucion
ContribucionController -> Interfaz_De_Usuario: context.redirect("/contribucionExitosa")
activate Interfaz_De_Usuario
deactivate ContribucionController

Interfaz_De_Usuario -> PersonaHumana: context.redirect("/contribucionExitosa")

@enduml
