@startuml Reporte Visita Tecnica

actor Colaborador
boundary Interfaz_De_Usuario
control FallaTecnicaController
entity FallaTecnicaBuilder
entity Heladera
entity FallaTecnica
entity SistemaDeGeolocalizacion
entity Tecnico
entity SufrioDesperfecto
entity Suscriptor
database BaseDeDatos

Colaborador -> Interfaz_De_Usuario: registrar nueva falla tecnica
activate Colaborador
activate Interfaz_De_Usuario
Interfaz_De_Usuario -> FallaTecnicaController: save(Context context)
activate FallaTecnicaController
activate FallaTecnicaBuilder
FallaTecnicaController -> FallaTecnicaBuilder: new FallaTecnicaBuilder()
activate BaseDeDatos
FallaTecnicaBuilder -> BaseDeDatos: Repo.search(idHeladera)
BaseDeDatos -> FallaTecnicaBuilder: heladera
deactivate BaseDeDatos
activate Heladera
FallaTecnicaBuilder -> Heladera : setEstadoActual (NO_DISPONIBLE)
FallaTecnicaBuilder -> Heladera : generarNuevaPublicacion(SUFRIO_DESPERFECTO)
activate SufrioDesperfecto
Heladera -> SufrioDesperfecto : update(Heladera, Publicacion)
SufrioDesperfecto -> Suscriptor : notify()
deactivate SufrioDesperfecto
activate Suscriptor
deactivate Heladera
FallaTecnicaController -> FallaTecnicaBuilder: construir()
deactivate Suscriptor
deactivate FallaTecnicaBuilder
activate FallaTecnica
deactivate FallaTecnica
activate SistemaDeGeolocalizacion
FallaTecnicaController -> FallaTecnica: avisarATecnico()
FallaTecnica -> SistemaDeGeolocalizacion: TecnicoMasCercano()
SistemaDeGeolocalizacion -> FallaTecnica : tecnico
deactivate SistemaDeGeolocalizacion
activate Tecnico
FallaTecnica -> Tecnico : notify()
deactivate Tecnico
deactivate FallaTecnica
FallaTecnicaController -> BaseDeDatos: Repo.agregar(fallaTecnica)
activate BaseDeDatos
deactivate BaseDeDatos
FallaTecnicaController -> Interfaz_De_Usuario: redirect("/incidentes")
deactivate FallaTecnicaController
Interfaz_De_Usuario -> Colaborador: falla tecnica registrada

@enduml