public class TestEntrega1 {

    // TEST UNA PERSONA HUMANA HACE DOS DONACIONES
    // TEST UNA PERSONA HUMANA INTENTA HACER UNA DONACION JURIDICA Y TIRA 403
    // TEST UNA PERSONA JURIDICA HACE UNA DONACION
    // TEST UNA PERSONA JURIDICA TRATANDO DE HACER UNA DONACION HUMANA Y TIRA 403



}
