@startuml GenerarDonacionDeDinero
actor Colaborador
boundary Interfaz_De_Usuario
control Controlador_De_Rol
entity Donacion_De_Dinero

Colaborador->Interfaz_De_Usuario: Generar donacion de dinero

Interfaz_De_Usuario->Controlador_De_Rol: Controlar Rol
Controlador_De_Rol->Controlador_De_Rol: Validar Datos


alt Sin permisos
    Controlador_De_Rol->Interfaz_De_Usuario: Sin permisos
    Interfaz_De_Usuario->Colaborador: Acceso Denegado
end

Controlador_De_Rol->Donacion_De_Dinero: Donar Dinero
Donacion_De_Dinero->Controlador_De_Rol: OK
Controlador_De_Rol->Interfaz_De_Usuario: OK
Interfaz_De_Usuario->Colaborador: OK
@enduml
