@startuml GenerarRegistroDeVisita

actor Tecnico
boundary Interfaz_De_Usuario
control TecnicoController
entity Registro_De_Visita
entity Heladera

Tecnico->Interfaz_De_Usuario: Generar registro de visita
activate Interfaz_De_Usuario

Interfaz_De_Usuario->TecnicoController: create(Context)
activate TecnicoController
TecnicoController -> TecnicoController: estaLogueado(Context context)

alt Sin permisos
    TecnicoController->Interfaz_De_Usuario: Sin permisos
    Interfaz_De_Usuario->Tecnico: Acceso denegado
else Con permisos
    TecnicoController->Registro_De_Visita: Crear registro de visita
    activate Registro_De_Visita
deactivate TecnicoController
deactivate Interfaz_De_Usuario
end

alt Se soluciono el problema
    Registro_De_Visita->Heladera: Marcar como activa
    activate Heladera
    deactivate Heladera
end


Registro_De_Visita->Interfaz_De_Usuario:Registro creado con exito
activate Interfaz_De_Usuario
Interfaz_De_Usuario->Tecnico: Mostrar mensaje de exito
activate Tecnico
deactivate Interfaz_De_Usuario

@enduml