@startuml Sensor de Temperatura - Actualizacion de Temperatura

entity RabbitMQAdapter
entity FactoryPublicacion
entity Publicacion
entity Heladera
entity Incidente

database BaseDeDatosAlerta

activate RabbitMQAdapter
RabbitMQAdapter -> FactoryPublicacion: Publicacion(type)
activate FactoryPublicacion
FactoryPublicacion -> RabbitMQAdapter: Publicacion
deactivate FactoryPublicacion
RabbitMQAdapter -> Publicacion: handleMessage(jsonMessage)
deactivate RabbitMQAdapter
activate Publicacion
activate Heladera
Publicacion -> Heladera: setTemperaturaActual(Double.parseDouble(temperatura))
Publicacion -> Heladera: getSensorTemperatura().activar()
deactivate Publicacion
Heladera -> Heladera: tareaProgramada.ejecutarTareaPrograma(5,this,"chequear")
Heladera -> Heladera: notify()
Heladera -> Incidente: setId()
activate Incidente
deactivate Incidente
Heladera -> BaseDeDatosAlerta: getInstance().agregar(incidente)
activate BaseDeDatosAlerta
deactivate BaseDeDatosAlerta
Heladera -> Heladera: tareaProgramada.pausarTarea();
deactivate Heladera

@enduml