@startuml Sensor de Temperatura - Actualizacion de Temperatura

actor RabbitMQ

entity RabbitMQAdapter
entity FactoryPublicacion
control ActualizacionTemperaturaController
entity Heladera
entity Incidente
entity SensorDeTemperatura
entity ChromeTask

RabbitMQ -> RabbitMQAdapter: jsonMessage
activate RabbitMQ
deactivate RabbitMQ
activate RabbitMQAdapter
RabbitMQAdapter -> FactoryPublicacion: Publicacion(type)
activate FactoryPublicacion
FactoryPublicacion -> RabbitMQAdapter: Publicacion
deactivate FactoryPublicacion
RabbitMQAdapter -> ActualizacionTemperaturaController: handleMessage(jsonMessage)
deactivate RabbitMQAdapter
activate ActualizacionTemperaturaController
ActualizacionTemperaturaController -> SensorDeTemperatura: activar()
activate SensorDeTemperatura
activate Heladera
ActualizacionTemperaturaController -> Heladera: setTemperaturaActual(Double.parseDouble(temperatura))
deactivate ActualizacionTemperaturaController
SensorDeTemperatura -> ChromeTask: ejecutarTareaPrograma(5,this,"chequear")
activate ChromeTask
deactivate ChromeTask
SensorDeTemperatura -> Heladera: notify()
deactivate Heladera
SensorDeTemperatura -> Incidente: setId()
activate Incidente
deactivate Incidente
SensorDeTemperatura -> ChromeTask: pausarTarea();
activate ChromeTask
deactivate ChromeTask
deactivate SensorDeTemperatura

@enduml